name: Local

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action name'
        required: true
        default: 'sync'
      appName:
        description: 'Application name'
        required: true
        default: 'blog'

jobs:
  local_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ./
      - name: Self test
        id: selftest
        uses: nholuongut/argocd-actions@v1
        with:
          address: ${{ secrets.ARGOCD_ADDR }}
          token: ${{ secrets.ARGOCD_TOKEN }}
          action: ${{ github.event.inputs.action }}
          appName: ${{ github.event.inputs.appName }}


